#!/bin/bash

### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


function memcached_start {
    /data/opt/memcached/bin/memcached -u www &
}
case "$1" in
	start)		memcached_start;;
	*)			echo "Usage: $0 {start}"; exit 1;;
esac
