#!/bin/bash

##############################################################
# title		: gentoo tiny installer
# authors	: keminar
# contact	: https://github.com/keminar/linux-tools
# date		: 05.04.2014
# license	: GPLv2
# usage		: run ./tiny.sh
##############################################################

# disk
DISK='sda'
BOOT='sda1'
SWAP='sda2'
ROOT='sda3'

# colors
unset OFF GREEN RED
OFF='\e[1;0m'
GREEN='\e[1;32m'
RED='\e[1;31m'
readonly OFF GREEN RED

# start
function tiny_start
{
	printf "$GREEN"
cat << EOF
-------------------------------
           Gentoo linux
        Tiny install start
-------------------------------
EOF
	printf "$OFF"
}

# set disk
function tiny_setdisk
{
	lsblk
	read -p "Select disk [sda|hda]: " disk
	disk=${disk:-$DISK}
	[[ $(lsblk -dno TYPE "/dev/$disk") = 'disk' ]] || tiny_setdisk
	DISK=$disk
}

# fdisk
function tiny_fdisk_boot
{
	fdisk /dev/$DISK
	fdisk -l /dev/$DISK
	while :; do
		read -p "Which partition will be /boot [$BOOT]: " part
		part=${part:-$BOOT}
		[[ $(lsblk -dno TYPE "/dev/$part") = 'part' ]] && break
	done
	boot=`fdisk -l /dev/$DISK|grep "/dev/$part "|awk '{print $2}'`
	if [ "$boot" != "*" ];then
		printf "$RED"
		printf "Please make /dev/$part as boot flag"
		printf "$OFF"
		tiny_fdisk
		return
	fi

	read -p "Do you want to format ${part} partition use mkfs.ext4 [n|y]: " ans
	if [ "$ans" = "y" ]; then
		mkfs.ext4 /dev/$part
	fi
	BOOT=$part
}

# fdisk
function tiny_fdisk_swap
{
	fdisk /dev/$DISK
	fdisk -l /dev/$DISK
	while :; do
		read -p "Which partition will be swap [$SWAP]: " part
		part=${part:-$SWAP}
		[[ $(lsblk -dno TYPE "/dev/$part") = 'part' ]] && break
	done

	mkswap /dev/$part
	swapon /dev/$part
	SWAP=$part
}

# fdisk
function tiny_fdisk_root
{
	fdisk /dev/$DISK
	fdisk -l /dev/$DISK
	while :; do
		read -p "Which partition will be / [$ROOT]: " part
		part=${part:-$ROOT}
		[[ $(lsblk -dno TYPE "/dev/$part") = 'part' ]] && break
	done

	read -p "Do you want to format ${part} partition use mkfs.ext4 [n|y]: " ans
	if [ "$ans" = "y" ]; then
		mkfs.ext4 /dev/$part
	fi
	ROOT=$part
}

function tiny_mount
{
	mount /dev/$ROOT /mnt/gentoo
	mkdir /mnt/gentoo/boot
	mount /dev/$BOOT /mnt/gentoo/boot
}


tiny_start
tiny_setdisk
tiny_fdisk_boot
tiny_fdisk_swap
tiny_fdisk_root
tiny_mount
